services:
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "50050:50050"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "50051:50051"

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "50052:50052"